### ISSUE TITLE
SW re-writing update.asar

### ISSUE THREAD

**Issue by Thyssenkrupp234** [jbsparrow/SWM-Mod#1]
When moving the modded update.asar file into the SW resources folder, Script-Ware proceeds to reinstall the application, (removing update.asar and replacing it with normal one) and then asks for a login. Even after running the chmod +x command to turn it to an executable, it still overwrites the file.

Any solution, thanks.

**Comment by Thyssenkrupp234** [comment]
This thing is unmaintained, so who cares

**Comment by jbsparrow** [comment]
Yeah, I haven't used Script-Ware Mac in ages. I'll try to update this for you sometime this week.
